version: "3.9"
services:
  dev:
    image: ${PROJECT}:${USER_UID}
    container_name: ${PROJECT}_${USER_UID}

    build:
      context: ../../context/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:12.2.2-cudnn8-devel-ubuntu20.04
        USERNAME: ${USER}
        USER_UID: ${USER_UID}
        PYTHON_MAJOR_VERSION: 3
        PYTHON_MINOR_VERSION: 10
        PYTHON_PATCH_VERSION: 12
        POETRY_VERSION: "2.1.2"

    volumes:
      - type: bind
        source: ${PARENT_DIR}/${PROJECT}
        target: /home/${USER}/${PROJECT}
      - type: bind
        source: ${HOME}/.ssh
        target: /home/${USER}/.ssh
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/${USER}/.gitconfig

    # ports: 
    #   - '8888:8888'

    working_dir: /home/${USER}/${PROJECT}
    tty: true

    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    environment:
      - POETRY_CACHE_DIR=/home/${USER}/${PROJECT}/.cache/pypoetry
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
      
    restart: always
    shm_size: '16gb'
    command: /bin/bash
    ulimits:
      memlock: -1


